/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioTres;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        
        System.out.println("Informe a distância percorrida pelo veículo:");
        int a = sc.nextInt();
        
        System.out.println("Informe o total de combustível consumido em litros:");
        int b = sc.nextInt();
        
        int consumoMedio = a/b;
        
        System.out.println("Consumo Médio de combustível por km: " + consumoMedio);    
    }
}
