/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioVinteEOito;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);

        String nome;
        double salario, salarioMinimo, reajuste = 0, salarioFinal, totalReajuste = 0, aux;

        System.out.println("Informe o valor do salário mínimo: ");
        salarioMinimo = sc.nextDouble();
        
        for (int i = 0; i < 584; i++) {
            System.out.println("Informe o nome do funcionário: ");
            nome = sc.next();

            System.out.println("Informe o salário do funcionário: ");
            salario = sc.nextDouble();

            aux = salario / salarioMinimo;

            if (aux < 3) {
                reajuste = salario * 0.50;
            } 
            else if (aux >= 3 && aux <= 10){
                reajuste = salario * 0.20;
            }
            else if (aux > 10 && aux <= 20){
                reajuste = salario * 0.15;
            } else {
                reajuste = salario * 0.10;
            }
            
            salarioFinal = salario + reajuste;
            totalReajuste = totalReajuste + reajuste;
            System.out.println("Nome: "+ nome 
                    + "\nReajuste: " + reajuste 
                    + "\nSalário final:" + salarioFinal);
        }
        System.out.println("**Total reajustado pela empresa: " + totalReajuste + "**");
    }
}
