/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioQuatro;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        
        System.out.println("Informe o nome do vendedor:");
        String nomeVendedor = sc.nextLine();
        
        System.out.println("Informe o salário do vendedor:");
        double salario = sc.nextDouble();
        
        System.out.println("Informe o total de vendas efetuadas pelo vendedor no mês (em dinheiro):");
        double qtdVendas = sc.nextDouble();
        
        double salarioFinal = salario + (qtdVendas * 0.15);
        
        
        System.out.println("O vendedor " + nomeVendedor + " possui o salário no valor de " + salario 
                + " terá o salário ao final do mês no valor de " + salarioFinal + " reais");    
    }
}
