/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioTrintaEUm;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        double a, b, total = 0;
        char c;

        System.out.println("Insira dois números:");
        a = sc.nextDouble();
        b = sc.nextDouble();

        System.out.println("Informe o operador aritmético --> +, -, /, *:");
        c = sc.next().charAt(0);

        switch (c) {
            case '+' -> total = a + b;
            case '-' -> total = a - b;
            case '/' -> {
                if (b == 0) {
                    System.out.println("Divisão por 0 não pode ser executada!");
                } else {
                    total = a / b;
                }
            }
            case '*' -> total = a * b;
            default -> System.out.println("Favor inserir um operador válido!");
        }
        System.out.println("Resultado: " + total);
    }
}
