/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioVinteESete;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        double valorVeiculo, valorDesc = 0, valorCliente;
        char combustivel;

        do {
            System.out.println("Informe o valor do veículo: ");
            valorVeiculo = sc.nextDouble();
            System.out.println("Informe o tipo de combustível do veículo (A - Álcool, G - Gasolina, D - Diesel:");
            combustivel = sc.next().charAt(0);

            if (combustivel == 'A' || combustivel == 'a') {
                valorDesc = valorVeiculo * 0.25;
            }
            else if (combustivel == 'G' || combustivel == 'g') {
                valorDesc = valorVeiculo * 0.21;
            }
            else if (combustivel == 'D' || combustivel == 'd') {
                valorDesc = valorVeiculo * 0.14;
            } else {
                System.out.println("Favor informar um valor válido!");
            }

            valorCliente = valorVeiculo - valorDesc;
            System.out.println("Valor do veículo para o cliente: " + valorCliente
                    + "\nDesconto concedido: " + valorDesc);

        } while (valorVeiculo != 0);

    }
}
