/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioUm;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        
        System.out.println("Escreva 2 números:");
        
        int a = sc.nextInt();
        int b = sc.nextInt();
        
        int soma = a +b;
        
        System.out.println("Soma: " + soma);
        
        
    }
}
