/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioVinteETres;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        
        System.out.println("Informe um número: ");
        int n = sc.nextInt();
        
        if (n > 80 || n < 25 || n == 40){
            System.out.println("Número dentro do intervalo");
        } else {
            System.out.println("Fora do intervalo");
        }
        
    }
}
