/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioVinteESeis;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        System.out.println("Informe um número de 1 a 5: ");
        int nr = sc.nextInt();

        switch (nr) {

            case 1 -> System.out.println("UM");

            case 2 -> System.out.println("DOIS");

            case 3 -> System.out.println("TRES");

            case 4 -> System.out.println("QUATRO");

            case 5 -> System.out.println("CINCO");

            default -> System.out.println("Número inválido!");
        }
        sc.close();
    }
}
